### PR TITLE
Add basic .travis.yml to run tests and linting

### PR DESCRIPTION
**Pull request by wlach**

### CODE REVIEW

**Comment by wlach** [comment]
One of @bcolloran or @hamilton (as organization owners) needs to grant travis access to this organization before we can test this.

**Comment by bcolloran** [comment]
awesome! thanks wlach, i'll figure out how to do that :-)

**Comment by bcolloran** [comment]
in the meantime, this appears to me zero-risk to merge, so i'll go ahead and do that

**Comment by bcolloran** [comment]
ok @wlach , i think i did this -- when i look at
https://github.com/iodide-project/iodide/settings/installations
i see "Travis CI" listed, so i think the access should be granted

**Comment by bcolloran** [comment]
follow up: i just got an email about the build status, which can be checked here:
https://travis-ci.org/iodide-project/iodide/builds/340323423?utm_source=email&utm_medium=notification

**Comment by bcolloran** [comment]
hmm fwiw, it looks like travis is way behind on node versions. I have
```
$ node --version
v8.9.4
$ npm --version
5.6.0
```
but the travis logs have 
```
$ node --version
v0.10.48
$ npm --version
2.15.1
```

possibly related to those travis errors around sync-exec, which is described thus:

```
sync-exec
An fs.execSync replacement until you get it natively from node 0.12+
Upgrading to 0.12.x is usually safe. At that point it will use child_process.execSync.
```

**Comment by bcolloran** [comment]
ok, i added a couple lines in travis.yaml to bump the node version, and it seems to be working now.

thanks so much for getting this ball rolling william, i wouldn't have evev known where to start!! :-) 💯

**Comment by wlach** [comment]
@bcolloran awesome, I was actually planning on fixing this myself before merging. Anyway, glad we have this infrastructure in place.

**Pull request merged**
