### PR TITLE
Action creator test

### PR DESCRIPTION
**Pull request by quinhill**
We noticed that you have more action creators to test. Should we write more tests for each of those?

### CODE REVIEW

**Comment by bcolloran** [comment]
Hi @quinhill, thank you for contributing to Iodide!

This looks good so far; I've requested one code change in a comment, and please also add a test for the case of passing an argument to that action creator.

Regarding other action creator tests, please be sure to read https://github.com/iodide-project/iodide/blob/master/CONTRIBUTING.md#testing -- tests for action creators like the one you've submitted are great, because that function has behaves in different ways depending on it's input. However, we don't need tests for actions creators that are purely declarative or that are pure simple pass-throughs of their arguments -- for example, these two don't need to be tested, because they don't really have any "logic" per se.

```
export function deleteNotebook(title) {
  return {
    type: 'DELETE_NOTEBOOK',
    title,
  }
}

export function newNotebook() {
  return {
    type: 'NEW_NOTEBOOK',
  }
}
```

**Comment by quinhill** [comment]
thank you for your feedback - we’ll work on that. Can you point us to the comment you left? We can’t find it in this PR.

**Comment by quinhill** [comment]
We've updated the description of that 'it' block. I just used your suggestion. Could you check if that's what you had in mind?

**Comment by bcolloran** [comment]
Yes the is fine, thanks. Please also add a test for the case of passing an argument to that action creator. And probably no need to commit your .gitignore

thanks  @quinhill !

**Comment by quinhill** [comment]
Sorry about the .gitignore file. Ran into some trouble committing locally. We added some more tests to the action creator test suite. We'll happily incorporate any feedback.

**Comment by bcolloran** [comment]
thanks @quinhill, looking pretty good. Again, we don't need tests for action creators that are purely declarative and have zero logic like `clearVariables()` and `newNotebook()`, so those can be trimmed; our testing strategy is that we want to test _logic_ not _code_ . Testing things that are purely declarative amounts to copy/pasting things from one place to another, and means you have to update twice the boilerplate when you make a change. I highly recommend reading those articles, they helped me a lot! :-)

Also, note that there is still an errant change in the .gitignore

thanks!!

**Comment by bcolloran** [comment]
@hamilton, i'm going to assign this to you to help @quinhill get this over the line since i'll be out next week

**Comment by jeremiahjstanley** [comment]
Hey @bcolloran, we'd like to withdrawal this PR, so that we can squash the commits and submit a clean PR. I linted the test file and made the 'it' blocks more descriptive. Could I get some additional clarification on the type of test you're looking for? 

Sorry for the confusion!

**Comment by bcolloran** [comment]
hi @jeremiahjstanley yes of course feel free to close this PR and submit another.

Regarding the tests: did you read the articles linked at: https://github.com/iodide-project/iodide/blob/master/CONTRIBUTING.md#testing ? LMK, because if those references were not clear or not helpful, I'll add more (and explain a bit more here)-- I want to make sure the resources are helpful for people coming to this project. If you haven't found the time to read those links yet, I highly recommend them. They make a number of subtle and useful points about testing.

Thanks so much @jeremiahjstanley and @quinhill !

**Pull request closed without merging**
