### PR TITLE
Include terms of service information in footer for official site (fixes #1145)

### LINKED ISSUE #1145: Add footer for public site with copyright/tos information
Per legal's advice, we should provide various copyright notices and terms of use in the footer.

### PR DESCRIPTION
**Pull request by wlach**

### CODE REVIEW

**Comment by wlach** [comment]
Here's what the footer looks like:

image

Terms/Privacy/Cookie links are same as on MDN.

**Comment by wlach** [comment]
Note that the terms and copyright notices will only be displayed if the `MOZILLA_OFFICIAL` environment variable is defined -- this lets us leave them out in contexts where they are not appropriate/valid (e.g. the internal mozilla deployment)

**Comment by bcolloran** [comment]
I think it looks great. I might change the env var name to something like `IODIDE_PUBLIC_TOS`, b/c `MOZILLA_OFFICIAL` might be confused with e.g. our "official _internal_ deployment" or something. But i'm willing to defer to strong feelings on the matter. Other than that, looks good to me

**Comment by bcolloran** [comment]
oh, and Michael Feldman's advice: """take out the "site licened under the MPL" in the footer. We usually leave that to the Github repo. Github has the code license. The website has the website license. """

**Comment by wlach** [comment]
Good calls, will adjust and then merge.

**Comment by wlach** [comment]
@bcolloran can you take another look and squashmerge if this looks ok to you?

**Comment by bcolloran** [comment]
looks great thanks will!

**Pull request merged**
