### PR TITLE
typo

### PR DESCRIPTION
**Pull request by Fil**

### CODE REVIEW

**Comment by hamilton** [comment]
Thanks for the PR @Fil :)

**Comment by Fil** [comment]
Cool. I was not able to run the python example, maybe it's not ready for consumption yet?

**Comment by hamilton** [comment]
Do you have ad blockers on both browsers?

**Comment by Fil** [comment]
Yes!
Now (on FF) it runs a bit further, and then I get

AttributeError: module 'pandas' has no attribute 'read_csv'


-- Fil

**Comment by mdboom** [comment]
Thanks for trying this out, @Fil!  Why don't we move this discussion over to its own issue in iodide-project/pyodide?  If there's any error messages in your Javascript console, those might be helpful...

**Comment by mdboom** [comment]
Also, try turning off any ad blockers / tracking blockers if you have them -- that's been causing issues for other folks.

**Pull request merged**
