### PR TITLE
Fix missing keys warning in array output handler

### PR DESCRIPTION
**Pull request by mdboom**
This fixes the warning in @hamilton 's comment [here](https://github.com/iodide-project/iodide/issues/359#issuecomment-369792086).

### CODE REVIEW

**Comment by bcolloran** [comment]
@mdboom i was still getting those warnings -- i think the issue was the unkeyed `<span>`s returned in `scalarHandler`. I wrapped each scalarHandler in a keyed span, which seems to clear the console warning for me. Added bonus: now array elts also show a tooltip that gives the array index for the hovered elt :-)

lmk what you think!

**Comment by bcolloran** [comment]
oh, i also merged in the latest master. i believe it will require an `npm install` to verify this latest update

**Comment by mdboom** [comment]
Thanks!  I guess this can be closed then.

**Comment by bcolloran** [comment]
oops, sorry, that was unclear-- i meant to say: i merged the latest master into this branch, but i haven't yet merged this branch back into master.

If these changes to you branch look ok to you and everything works as desired, we can go ahead and merge (you have merge permissions right?)

**Comment by mdboom** [comment]
Ah, got it.  LGTM.  Merging.

**Pull request merged**
