### PR TITLE
Migrating autosave from localstroage to indexDB

### PR DESCRIPTION
**Pull request by iFlameing**
@walch can you review this  and merge since I updated test and now it is ready for merge.

### CODE REVIEW

**Comment by wlach** [comment]
@iFlameing looks like the tests are failing for reasons that have to do with the PR.

**Comment by iFlameing** [comment]
@wlach  sorry for this the test are failing after the rebase .

**Comment by iFlameing** [comment]
@walch I am closing this and opening a new one because I think I messed up my branch due to rebase.

**Comment by wlach** [comment]
It appears that the test failures are due to some other circle issue. After the nits in the review are addressed, I think I'm ok merging this as soon as we sort that out and can verify the tests are passing. Thanks for your work on this!

**Pull request closed without merging**
