### PR TITLE
[WIP] menu UI refactor

### PR DESCRIPTION
**Pull request by hamilton**
This work ended up being a major refactoring of about half the component code base - all the menus, buttons, and UI components that are _not_ part of the cell set - to work with our `UserTask` class. 

It:

- [x] migrates to material-ui v1 (`@next`), which works a bit more smoothly / is more performant / is more composable than `@latest`
- [x] refactors all the menus to use the new `UserTask` item
- [x] matches styling and tasks of the previous menu
- [x] migrates the examples to use the new external url task
- [x] makes just about every component a container component, while following the `propTypes` / unconnected conventions found in the cells
- [x] finishes some of the reorg into the right directories
- [x] tests for the unconnected components are necessary

This should fix: #405, fix (partly) #395, #393, #390, #389, #319, #176, #160, and lay the groundwork for closing #162.

### CODE REVIEW

**Comment by hamilton** [comment]
It turns out my approach simply breaks material ui's oldest `@latest` version. It wasn't obvious when we started this library that `@latest` was actually heavily discouraged in favor of `@next`, the beta version of v1. It turns out it makes a big difference. So I'm going to be porting over the entire app to `@next` and see if it will solve some of the various click / keyboard issues I'm facing now with these composed menu items. On the whole this is an annoyance and is quite a refactor to go ontop of this refactor, but it feels necessary. Hoping to have this ready for review by Thursday.

**Comment by hamilton** [comment]
I've migrated most of the code base to the beta version of `material-ui`, and everything works as expected now, though some styling is slightly different. 

Drawers do not automatically close on `esc` - we should see if that should be expected behavior.

**Comment by hamilton** [comment]
Worked through an extensive QA process w/ @bcolloran. As soon as the tests pass, we are going to merge this.

On the whole, this refactor solves a lot of problems around our UI components, but it also introduces some additional issues and surfaces some rough edges we should check on. Drawers are a bit rough now, since material-ui has updated.

**Comment by bcolloran** [comment]
:100: great work @hamilton

**Pull request merged**
