### PR TITLE
Simplify report pane logic and add tests

### PR DESCRIPTION
**Pull request by wlach**
Before this change, any change to an md/css cell would invalidate
all non-markdown cells (e.g. cells generated by a language plugin
output renderer). With this change, those changes are kept intact
while markdown/css changes are incorporated into the report.

### Pull Request checklist

- [N/A] **Documentation**: If this feature has or requires documentation, the relevant docs have been updated.
- [x] **Changelog**: This PR updates the [changelog](https://github.com/iodide-project/iodide/blob/master/CHANGELOG.md) with any user-visible changes.
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not

### CODE REVIEW

**Comment by wlach** [comment]
@bcolloran is there any reason not to do things this way? I based this approach on this document:

https://reactjs.org/docs/integrating-with-other-libraries.html

It seems to work great for notebooks like this, where you have one cell outputting some stuff in response to a language plugin, with explanatory markdown around it: https://definitely-staging.iodide.io/notebooks/168/

Without this change you are constantly having to re-run the language plugin cell as you edit text. This is not quite as good as #2175 but gets us a little closer.

**Comment by wlach** [comment]
Went ahead and added some jest tests for this piece while I was at it.

**Comment by bcolloran** [comment]
@wlach this code looks fine to me, but i'm confused about the behavior --
when i edit the md or css in this notebook on release the mermaid chart is not affected: https://alpha.iodide.io/notebooks/3470/

i don't seem to have to re-run the `mmd` chunk when i edit the css or md in either your notebook on staging or the the notebook on alpha, so i'm confused that maybe i'm missing something?

**Comment by wlach** [comment]
I think I misunderstood the code here, and it turns out there is not an actual bug. But the simplifications here are still worthwhile. I'll remove the entry from the changelog and change the commit message and just land it.

**Pull request merged**
