### PR TITLE
add a usable default stylesheet & partition out presentation css from app style

### LINKED ISSUE #331: CSS might have regressed without bootstrap reset and basic styles.
might be worth seeing whether we like the basic bootstrap styles (without all of their crazy buttons and grids and stuff). Presentation mode is looking a little shabby

### PR DESCRIPTION
**Pull request by hamilton**
This should close #331, #237, parts of #210, parts of #199. 

I've added a new default stylesheet for `user-markdown` which provides sensible report-style formatting.

Steps to test it out for yourself:

- run your dev server, and use what is in `dev/`
- add `?url=https://gist.githubusercontent.com/hamilton/436ca12593652f830dcb5b141d336b37/raw/283a7a9436d52742c4a109719b802eb262f2f5b1/default-presentation-2.html` to load an example (run all cells in presentation mode is broken so you will have to "run all" then switch to presentation mode"
- examine how we're handling style now.

### CODE REVIEW

**Comment by bcolloran** [comment]
it all looks really good, i only see one thing that looks a little off, which is the extra padding around user-markdown, i think maybe these styles.

```
.user-markdown:last-child {
    padding-bottom: 60px;
}
.user-markdown:first-child {
    padding-top: 30px;
}
```

this results in an extra 90px of whitespace between paragraphs if you have two consecutive MD cell.

Take a look at
` ?url=https://iodide-project.github.io/iodide-examples/what-a-web-notebook-looks-like.html `
for an example

peek 2018-03-13 23-12

Other than that little quibble, oh man it looks great!

**Comment by bcolloran** [comment]
Oh, i decided to spot check some other notebooks, (take a look at `?url=https://iodide-project.github.io/iodide-examples/output-handling.html`), and i noticed another issue:

If you're in "EDIT" view and your window is moderately wide (1150px or more) it's kind of jarring that the MD is centered rather than being aligned to the left side of the cell, so it might be best not to change the horizontal alignment in edit view (but i think having an 800px max width on the container is probably fine for edit view, as long as it's aligned to the left)

Also, the extra top/bottom padding really jumps out in that example.

image

**Comment by hamilton** [comment]
@bcolloran 

- good catches re: the margining on the top and bottom. There's still a bit of funky css inherent in presentation mode that I may need to work out, so it is clear that this solution was probably a bit too messy. Without that bit of css there is no comforting whitespace below or above the cell container, but the solution should be something a bit better than this (and obviously not as weird with multiple MD cells!)
- I like this idea about the editor & auto margining. It does indeed feel weird centered in the editor. This should be a really easy fix - set the margin to not auto for editor.

**Comment by hamilton** [comment]
@bcolloran made those changes. Let me know what you think!

- editor mode rendered markdown is now left-aligned with the left edge of CodeMirror instances (so this is the gutter left edge of a js cell, which is less elegant, but the absolute left edge of a MD cell editor, which looks fine). The width is still ___px.
- the between-cell stuff is fixed, and I added a bit of padding between cells in presentation mode to look a lot more seamless (as if it were one big mdcell).

**Comment by bcolloran** [comment]
:clap: 

man, i really looks great! so very much improved, thank you hamilton! merging!

**Pull request merged**
