### PR TITLE
add a cell type selector label to each cell

### PR DESCRIPTION
**Pull request by hereisnaman**
resolved: https://github.com/iodide-project/iodide/issues/187
screen shot 2018-02-12 at 1 18 45 pm

### CODE REVIEW

**Comment by hamilton** [comment]
Hi @hereisnaman - thanks for the PR. I'm not sure we are actually settled on how we want to approach this, so I don't think we're ready to have this issue solved quite yet.

**Comment by hereisnaman** [comment]
Okay great.

**Comment by hamilton** [comment]
@hereisnaman the core devs chatted a bit about this today, and I think we're in fact going to take on this work ourselves, since it will dovetails nicely with a few other UI tweaks we're going to make.

**Comment by hereisnaman** [comment]
Okay good.

**Pull request closed without merging**
