### PR TITLE
Use Pyodide from netlify, rather than deploying with Iodide

### PR DESCRIPTION
**Pull request by mdboom**
### Pull Request checklist

- [ ] **Documentation**: If this feature has or requires documentation, the relevant docs have been updated.
- [ ] **Changelog**: This PR updates the [changelog](../CHANGELOG.md) with any user-visible changes.
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not

### CODE REVIEW

**Comment by mdboom** [comment]
Marking this as WIP -- there is a small glitch in the URL config on Pyodide's side.  Redeploying and hope to be back up in an hour.

**Comment by willingc** [comment]
Nice work @mdboom :smile: I'm getting over pneumonia but will likely be more active here this month.

**Comment by mdboom** [comment]
Oh that's terrible!  Hope you feel better soon, @willingc.

**Comment by mdboom** [comment]
Related documentation on the Pyodide side: https://github.com/iodide-project/pyodide/pull/455

**Pull request merged**
