### PR TITLE
Provide a modal describing what they are signing up for on iodide site (fixes #1147)

### LINKED ISSUE #1147: Provide more information to users before they sign up
Per legal, we should provide more information on what users are signing up for before they log into iodide.

I think we probably ought to not just hook directly into github's auth flow on the public server, but rather provide some kind of "login" modal which tells the user what they're consenting to.

### PR DESCRIPTION
**Pull request by wlach**

### CODE REVIEW

**Comment by wlach** [comment]
Ob screenshot:

image

**Comment by wlach** [comment]
Note, I arbitrarily mentioned the text about sharealike license as its what wikipedia + mdn used. We should obviously review the text here between ourselves and legal to make sure it communicates the right things before we launch.

**Comment by bcolloran** [comment]
in an email, Michael Feldman recommended that we should use CC BY-SA 3.0 -- https://creativecommons.org/licenses/by-sa/3.0/deed.en
perhaps we should mention that explicitly?

**Comment by wlach** [comment]
I'd personally lean against using jargon like `BY-SA` in the modal but `Attribution-ShareAlike 3.0 Unported` sounds fine to me.

**Comment by wlach** [comment]
Adjusted text per suggestions:

image

**Comment by wlach** [comment]
@hamilton gave the verbal ok to this, let's merge!

**Pull request merged**
