### PR TITLE
Delete settings.js

### PR DESCRIPTION
**Pull request by ganes1410**
this pull request addresses #504

### CODE REVIEW

**Comment by djbarnwal** [comment]
Hi, @ganes1410 while deleting `settings.js` you need to take care of all the other files which might be importing it. You need to search for all instances of `settings.label.AUTOSAVE` and `settings.lable.EXAMPLE` in the codebase and replace them by their string value.

**Comment by ganes1410** [comment]
my bad @djbarnwal .can i open a new pull request with the changes suggested?

**Comment by djbarnwal** [comment]
@ganes1410 Sure. Close this PR. Make necessary changes on a new branch and send another Pull Request.

**Comment by ganes1410** [comment]
ok @djbarnwal

**Comment by bcolloran** [comment]
@djbarnwal thank you for helping @ganes1410 get up and running on this issue!

**Pull request closed without merging**
