### PR TITLE
Wait for database before running migrations

### PR DESCRIPTION
**Pull request by nrgoncalves**
This prevents a race condition while launching the containers for
local development, whereby the migrations script is sometimes being
executed before the database is ready to accept connections.

This borrows the approach currently used in the CI pipeline, as suggested by @wlach 

https://github.com/iodide-project/iodide/blob/5c38c734420edb37ccff5ea3243d6125a498be8c/.circleci/config.yml#L140

### Pull Request checklist

- [ ] **Documentation**: Not sure if this needs to be documented
- [ ] **Changelog**: Infrastructure related change, so probably does not apply 
- [ ] **Tests**: Infrastructure related change, so probably does not apply

### CODE REVIEW

**Comment by wlach** [comment]
Looks good @nrgoncalves, just wanted to confirm that it fixes the problem for you before landing?

**Comment by wlach** [comment]
Oh, also, a quick Changelog entry would be good. Just using the title for this PR in the log should be enough.

**Comment by nrgoncalves** [comment]
thanks @wlach, I confirm that this works for me -- I tested on a couple of different machines and could not reproduce the issue.

**Comment by wlach** [comment]
Thanks so much!

**Pull request merged**
