### PR TITLE
Fix styling issues of history side pane with chrome

### LINKED ISSUE #417: history side pane has styling issues in Chrome when number of history items ecxeeds page height
This appears in `master` but only in Chrome, not Firefox. It appears to be an issue due to the migration to material-ui `1.0.0-beta35` in #408.

One solution may be to utilize the `Paper` component within the wrapping `SidePane` component.

__Steps to reproduce:__

1. Open any notebook in Chrome ([this link](https://iodide-project.github.io/master/?url=https://raw.githubusercontent.com/iodide-project/iodide-examples/master/output-handling.html) should do the trick)
2. run all cells
3. open the history pane

mar-01-2018 19-07-26

### PR DESCRIPTION
**Pull request by pradeepgangwar**
These small tweaks were able to fix this bug. I hope these changes are in acceptable range. Suggest changes if there is some other way.

Fixes #417 

screenshot from 2018-03-06 04-45-04

### CODE REVIEW

**Comment by bcolloran** [comment]
Was this tested on Firefox too? (To ensure it looks the same in both cases?)

**Comment by pradeepgangwar** [comment]
yes it works on Firefox too.

**Comment by bcolloran** [comment]
Perfect, thanks @pradeepgangwar. @hamilton, as our menus/panes/styling expert, can you review when you have time?

**Comment by hamilton** [comment]
Yes, this works on all platforms.

**Comment by hamilton** [comment]
thanks @pradeepgangwar!

**Pull request merged**
